#!/bin/bash
ON=1
OFF=0
PIN=0
ERROR_MSG_1='Done.'
ERROR_MSG_2='Already in progress.'
TWO_MINS=$((60*2))
DELAY=0.3

fileName='pid'
filePath='/tmp/garageDoor/'
file="$filePath$fileName"

gpio mode $PIN output

printOutput(){
    output="{\"success\":$3, \"exitCode\":\"$1\", \"msg\":\"$2\"}"
    len=${#output}

    echo "Cache-Control: no-cache"
    echo "pragma: no-cache"
    echo "HTTP/1.0 200 OK"
    echo "Content-Type: application/json"
    echo "Content-Length: $len"
    echo
    echo $output
}

on(){
    gpio mode $PIN up
    gpio write $PIN $ON
    echo $?
}

off(){
    gpio mode $PIN down
    gpio write $PIN $OFF
    echo $?
}

secElapsed(){
    echo expr $(date +%s) - $(date +%s -r $file)
}

turnOn(){
    mkdir -p $filePath
    echo $$ > $file
    ecode=$(on)
    rm $file
}

turnOff(){
    mkdir -p $filePath
    echo $$ > $file
    ecode=$(off)
    rm $file
}

if [ -e $file ]
then
    if [ secElapsed -gt $TWO_MINS ]
    then
        rm $file
        turnOn
        sleep $DELAY
        turnOff
        printOutput $ecode $ERROR_MSG_1 true
    else
        printOutput 1 "$ERROR_MSG_2 $(secElapsed)" false
        exit
    fi
else
    turnOn
    sleep $DELAY
    turnOff
    printOutput $ecode $ERROR_MSG_1 true
fi

exit
